### ISSUE TITLE
Unable to build the master branch

### ISSUE THREAD

**Issue by RamIndani** [Rajawali/RajawaliVR#14]
Hi,
I am not able to build the master, I get below error messages

C:\VR\RajawaliVR\RajawaliVR\rajawalivr\src\main\java\org\rajawali3d\vr\surface\R
ajawaliVRSurfaceView.java:64: error: cannot find symbol
    public void setAntiAliasingMode(ANTI_ALIASING_CONFIG anti_aliasing_config) {

                                    ^
  symbol:   class ANTI_ALIASING_CONFIG
  location: class RajawaliVRSurfaceView
C:\VR\RajawaliVR\RajawaliVR\rajawalivr\src\main\java\org\rajawali3d\vr\renderer\
RajawaliVRRenderer.java:91: error: cannot find symbol
        getCurrentCamera().updatePerspective(
                          ^
  symbol:   method updatePerspective(float,float,float,float)
  location: class Camera
C:\VR\RajawaliVR\RajawaliVR\rajawalivr\src\main\java\org\rajawali3d\vr\materials
\shaders\HotspotFragmentShader.java:123: error: method add in class AShaderBase.
ShaderVar cannot be applied to given types;
            ShaderVar yScale = sin(muTime.multiply(muTextureRotationSpeed)).mult
iply(0.5f).add(0.5f);

          ^
  required: AShaderBase.ShaderVar
  found: float
  reason: actual argument float cannot be converted to AShaderBase.ShaderVar by
method invocation conversion
C:\VR\RajawaliVR\RajawaliVR\rajawalivr\src\main\java\org\rajawali3d\vr\materials
\shaders\HotspotFragmentShader.java:154: error: cannot find symbol
            RFloat angle = new RFloat("angle", atan(uv.y(), uv.x()).multiply(-1)
);
                                               ^
  symbol:   method atan(AShaderBase.ShaderVar,AShaderBase.ShaderVar)
  location: class HotspotFragmentShader
C:\VR\RajawaliVR\RajawaliVR\rajawalivr\src\main\java\org\rajawali3d\vr\surface\R
ajawaliVRSurfaceView.java:31: error: RajawaliVRSurfaceView is not abstract and d
oes not override abstract method setUsesCovererageAntiAliasing(boolean) in IRaja
waliSurface
public class RajawaliVRSurfaceView extends CardboardView implements IRajawaliSur
face {
       ^
C:\VR\RajawaliVR\RajawaliVR\rajawalivr\src\main\java\org\rajawali3d\vr\surface\R
ajawaliVRSurfaceView.java:63: error: method does not override or implement a met
hod from a supertype
    @Override
    ^
C:\VR\RajawaliVR\RajawaliVR\rajawalivr\src\main\java\org\rajawali3d\vr\surface\R
ajawaliVRSurfaceView.java:68: error: method does not override or implement a met
hod from a supertype
    @Override
    ^
7 errors
:rajawalivr:compileReleaseJava FAILED

FAILURE: Build failed with an exception.

**Comment by drbago** [comment]
As of f55f2028a7b0456f9d63aa40ad07313a1b867062, I am having the same issues in this thread.

By looking at the [deps.gradle](https://github.com/Rajawali/RajawaliVR/blob/6402b93083b72a8cd47906e612a734ffd07067f7/RajawaliVR/deps.gradle) for this commit, you can see that RajawaliVR depends on a Maven snapshot, org.rajawali3d:rajawali:1.0.275-SNAPSHOT, which does not contain the symbols required -- such as atan. According to  to [oss.sonatype.org](https://oss.sonatype.org/#nexus-search;quick~rajawali), 1.0.275-SNAPSHOT was released on Jun 10 where atan was not introduced until Jun 18 (according to commit [3b160132](https://github.com/Rajawali/Rajawali/commit/3b1601324effb6d26aeb304195f20b350c2e643b)).  So, it seems that the version declared in dep.gradle is too old.

The earliest version that compiles for me is org.rajawali3d:rajawali:1.0.282-SNAPSHOT. To fix this bug, update the dependency to some well-tested snapshot >= 1.0.282.

**Comment by RamIndani** [comment]
Thank you for your input drbago, I used old branch and thatbworked for me

**Comment by Attect** [comment]
Thanks.It works!
