### ISSUE TITLE
RajawaliVR giving compile time errors

### ISSUE THREAD

**Issue by ParagRKadam** [Rajawali/RajawaliVR#16]
public void main() {
        //        vec2 uv = fragCoord.xy / iResolution.xy;
        RVec2 uv = new RVec2("uv", mvTextureCoord);
        //        float circleBorderHalf = circleBorder * 0.5;
        RFloat circleBorderHalf = new RFloat("circleBorderHalf");
        circleBorderHalf.assign(muBorderThickness.multiply(0.5f));

        //        float dist = distance(uv, circleCenter);
        ShaderVar dist = distance(uv, muCircleCenter);

        RVec4 outColor = new RVec4("outColor", new RVec4("vec4(0.0)"));
        //outColor.a().assign(0.0f);

        if(mUseTexture) {
            //        float yScale = sin(iGlobalTime * textureRotationSpeed) * 0.5 + 0.5;
            ShaderVar yScale = sin(muTime.multiply(muTextureRotationSpeed)).multiply(0.5f).add(0.5f);    //ERROR this line

/*

Error:(121, 91) error: method add in class AShaderBase.ShaderVar cannot be applied to given types;
required: AShaderBase.ShaderVar
found: float
reason: actual argument float cannot be converted to AShaderBase.ShaderVar by method invocation conversion

*/

            RFloat one = new RFloat("one", new RFloat(1.0f));
            //one.assign(1.0f);
            //        vec2 uvAnim = vec2(uv.x, uv.y - 0.5);
            RVec2 uvAnim = new RVec2("uvAnim", new RVec2("vec2(0.0)"));
            uvAnim.x().assign(uv.x());
            uvAnim.y().assign(uv.y().subtract(0.5f));
            //        uvAnim.y *= 1.0 / yScale;
            uvAnim.y().assignMultiply(one.divide(yScale));
            //        uvAnim.y += 0.5;
            uvAnim.y().assignAdd(0.5f);
            //        outColor = texture2D(iChannel0, uvAnim);
            RVec4 color = (RVec4)getGlobal(DefaultShaderVar.G_COLOR);
            outColor.assign(texture2D(muTexture, uvAnim));
        }

        //        if(dist < circleRadius + circleBorderHalf && dist > circleRadius - circleBorderHalf) {
        startif(
                new Condition(dist, Operator.LESS_THAN, muCircleRadius.add(circleBorderHalf)),
                new Condition(Operator.AND, dist, Operator.GREATER_THAN, muCircleRadius.subtract(circleBorderHalf))
        );
        {
            //            outColor = trackColor;
            outColor.assign(muTrackColor);
            //            float startAngle = 0.0;
            RFloat startAngle = new RFloat("startAngle", new RFloat(0));
            //            float endAngle = startAngle + mod(iGlobalTime * 2.0, PI_2);
            RFloat endAngle = new RFloat("endAngle", startAngle.add(muProgress.multiply(mcTwoPI)));
            //            uv -= circleCenter;
            uv.assignSubtract(muCircleCenter);
            //            float angle = -1.0 * atan(uv.y, uv.x) + PI;
            RFloat angle = new RFloat("angle", atan(uv.y(), uv.x()).multiply(-1)); //ERROR this line

/*

Error:(152, 48) error: cannot find symbol method atan(AShaderBase.ShaderVar,AShaderBase.ShaderVar)

*/

            angle.assignAdd(mcPI);

            //            if(angle >= startAngle && angle <= endAngle) {
            startif(new Condition(angle, Operator.GREATER_THAN_EQUALS, startAngle),
                    new Condition(Operator.AND, angle, Operator.LESS_THAN_EQUALS, endAngle));
            {
                //                outColor = progressColor;
                outColor.assign(muProgressColor);
            }
            endif();
        }
        endif();

        if(mDiscardAlpha) {
            startif(new Condition(outColor.a(), Operator.EQUALS, 0));
            {
                discard();
            }
            endif();
        }

        //        fragColor = outColor;
        GL_FRAG_COLOR.assign(outColor.getName());
    }

I downloaded the RajawaliVR project and it gives me two compile time errors in the class HotspotFragmentShader. Please fix it as soon as possible. Thank you :)

**Comment by punkete1990** [comment]
Yes, I have a temporary fix with this code:

First Error: Create a new RFloat(0.5f)
ShaderVar yScale = sin(muTime.multiply(muTextureRotationSpeed)).multiply(0.5f).add(new RFloat(0.5f));

Second Error: Create a new ShaderVar
ShaderVar s = new ShaderVar("atan(" + uv.y().getName() + ", " + uv.x().getName() + ")", DataType.FLOAT);            
RFloat angle = new RFloat("angle", s.multiply(-1));

**Comment by ParagRKadam** [comment]
Thanks its a good workaround.
