### ISSUE TITLE
how to tell whether the camera is looking at an object

### ISSUE THREAD

**Issue by flankechen** [Rajawali/RajawaliVR#2]
I render an plane with size(1,1) right on the screen like: mPlane.setZ(-4);
how to tell whether I am looking at the object? 
how to get the camera matrix, model matrix, head matrix?  Do I have to calculate the picth and yaw by my self?

I check the code and find private member 
private Quaternion mCameraOrientation;
which returns value from -1 to 1 (360). it's this possible to use this to tell whether I am looking at the plane?

Thanks!

**Comment by uzman** [comment]
did you find a solution?
i put a sphere on the scene. but i don't get if camera is looking at it?
any help please?

**Comment by flankechen** [comment]
I learn this from cardboard example. Rajawali engine gives you more freedom in developing, and feels go for both "opengles" and "engine" guys.

	//check if the object is looking at by the camera
	private boolean isLookingAtObject(Object3D object) {
		float[] initVec = {0, 0, 0, 1.0f};
        float[] objPositionVec = new float[4];
		
        // Convert object space to camera space. Use the headView from onNewFrame.
        mModelMatrix = object.getModelMatrix().getFloatValues();
        Matrix.multiplyMM(mModelView, 0, mHeadViewMatrix, 0, mModelMatrix, 0);
        Matrix.multiplyMV(objPositionVec, 0, mModelView, 0, initVec, 0);
        
        float pitch = (float)Math.atan2(objPositionVec[1], -objPositionVec[2]);
        float yaw = (float)Math.atan2(objPositionVec[0], -objPositionVec[2]);
		
//        Log.i(TAG, "Object position: X: " + objPositionVec[0]
//                + "  Y: " + objPositionVec[1] + " Z: " + objPositionVec[2]);
//        Log.i(TAG, "Object Pitch: " + pitch +"  Yaw: " + yaw);
        
        return (Math.abs(pitch) < PITCH_LIMIT) && (Math.abs(yaw) < YAW_LIMIT);
	}

**Comment by niusounds** [comment]
This code works same as flankechen wrote. isn't it?

```java
//check if the object is looking at by the camera
private boolean isLookingAtObject(Camera camera, Object3D object) {

    Vector3 v = new Vector3(camera.getPosition());
    v.multiply(object.getModelViewMatrix());

    float pitch = (float) Math.atan2(v.y, -v.z);
    float yaw = (float) Math.atan2(v.x, -v.z);

    return (Math.abs(pitch) < PITCH_LIMIT) && (Math.abs(yaw) < YAW_LIMIT);
}
```

**Comment by MasDennis** [comment]
Closing this issue because it is answered.
